//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1_Console.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Article", Namespace="http://schemas.datacontract.org/2004/07/Zadatak_1_Service.Model")]
    [System.SerializableAttribute()]
    public partial class Article : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        Zadatak_1_Console.ServiceReference1.Article[] GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<Zadatak_1_Console.ServiceReference1.Article[]> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyArticles", ReplyAction="http://tempuri.org/IService1/BuyArticlesResponse")]
        void BuyArticles(Zadatak_1_Console.ServiceReference1.Article[] AllArticles, Zadatak_1_Console.ServiceReference1.Article article, int Quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyArticles", ReplyAction="http://tempuri.org/IService1/BuyArticlesResponse")]
        System.Threading.Tasks.Task BuyArticlesAsync(Zadatak_1_Console.ServiceReference1.Article[] AllArticles, Zadatak_1_Console.ServiceReference1.Article article, int Quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WriteToFile", ReplyAction="http://tempuri.org/IService1/WriteToFileResponse")]
        void WriteToFile(Zadatak_1_Console.ServiceReference1.Article[] AllArticles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WriteToFile", ReplyAction="http://tempuri.org/IService1/WriteToFileResponse")]
        System.Threading.Tasks.Task WriteToFileAsync(Zadatak_1_Console.ServiceReference1.Article[] AllArticles);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Zadatak_1_Console.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Zadatak_1_Console.ServiceReference1.IService1>, Zadatak_1_Console.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Zadatak_1_Console.ServiceReference1.Article[] GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<Zadatak_1_Console.ServiceReference1.Article[]> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public void BuyArticles(Zadatak_1_Console.ServiceReference1.Article[] AllArticles, Zadatak_1_Console.ServiceReference1.Article article, int Quantity) {
            base.Channel.BuyArticles(AllArticles, article, Quantity);
        }
        
        public System.Threading.Tasks.Task BuyArticlesAsync(Zadatak_1_Console.ServiceReference1.Article[] AllArticles, Zadatak_1_Console.ServiceReference1.Article article, int Quantity) {
            return base.Channel.BuyArticlesAsync(AllArticles, article, Quantity);
        }
        
        public void WriteToFile(Zadatak_1_Console.ServiceReference1.Article[] AllArticles) {
            base.Channel.WriteToFile(AllArticles);
        }
        
        public System.Threading.Tasks.Task WriteToFileAsync(Zadatak_1_Console.ServiceReference1.Article[] AllArticles) {
            return base.Channel.WriteToFileAsync(AllArticles);
        }
    }
}
